### ISSUE TITLE
Support for Kibana 5.3

### ISSUE THREAD

**Issue by MyDigitalLife** [clamarque/Kibana_health_metric_vis#10]
Any change you will be updating this plugin to support kibana 5.3?

**Comment by MyDigitalLife** [comment]
I tested it localy and it looks like the only thing needed is to update the version in package.json

**Comment by clamarque** [comment]
@MyDigitalLife  Hi! yes but you can send me a pull request for that I create a release with the latest version.

**Comment by clamarque** [comment]
@MyDigitalLife Thanks ! The release is available [here](https://github.com/clamarque/kibana_health_metric_vis/releases/tag/5.3.0)
