### ISSUE TITLE
Not compatible with Kibana 5.1.1

### ISSUE THREAD

**Issue by christad92** [clamarque/Kibana_health_metric_vis#12]
when i try to install, it returns the error:

> $ kibana-plugin.bat install https://github.com/clamarque/kibana_health_metric_vis/releases/download/v5.0/kibana_health_metric_vis-5.0.zip
> Attempting to transfer from https://github.com/clamarque/kibana_health_metric_vis/releases/download/v5.0/kibana_health_metric_vis-5.0.zip
> Transferring 33323 bytes....................
> Transfer complete
> Retrieving metadata from plugin archive
> Extracting plugin archive
> Extraction complete
> Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [health_metric_vis]. Expected [5.1.1]; found [5.0.0]"

**Comment by clamarque** [comment]
@christad92 Hi. It's normal. You install a version 5.0.0 on a kibana 5.1.1. Update the package.json with your version and try again.
