### ISSUE TITLE
Metric displaying wrong value Kibana 5.4.2

### ISSUE THREAD

**Issue by ThomasFlanaghan** [clamarque/Kibana_health_metric_vis#14]
Hi I changed the package.json to 5.4.2 and installed the plugin. All installs okay however the value displayed is different to the value returned. Attached screenshot showing the value displayed and the value returned. As you can see the result displayed is 6 however the response shows 6461. The normal metric visualisation that comes with Kibana displays correctly.
![image](https://user-images.githubusercontent.com/17478227/27739091-564246bc-5da5-11e7-8ae0-873982085d2a.png)

**Comment by tibobd** [comment]
Same issue on my side with Kibana 5.4.0 !

**Comment by clamarque** [comment]
@ThomasFlanaghan  Hi ! Do you have the bug with a result with 3 numbers too ? Can you test ? 
@tibobd . Can you send me a screen too ? Thanks you !

**Comment by clamarque** [comment]
Hi. The bug is fixed. You can download the new release (5.4.x)
