### ISSUE TITLE
Getting error for 5.5

### ISSUE THREAD

**Issue by austin-taylor** [clamarque/Kibana_health_metric_vis#15]

**Comment by austin-taylor** [comment]
Attempting to transfer from https://github.com/clamarque/kibana_health_metric_vis/releases/download/v5.4/kibana_health_metric_vis-5.4.0.zip
Transferring 36549 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [health_metric_vis]. Expected [5.5.0]; found [5.4.0]"

Submitting error per readme

**Comment by clamarque** [comment]
@austin-taylor You need to change the version in th file package.json with your version, please, read the README. Thanks

**Comment by austin-taylor** [comment]
I did try changing the package.json file from 5.4.0 to 5.5.0, but there must be something else on my end. Will continue to troubleshoot and thank you for the quick response.

**Comment by austin-taylor** [comment]
Had to re-zip the file and used this command `sudo /usr/share/kibana/bin/kibana-plugin install file:///opt/kibana/health_metric_5.5.0.zip` 

thanks again
