### ISSUE TITLE
Metric displaying wrong unit in Bytes.

### ISSUE THREAD

**Issue by ktlast** [clamarque/Kibana_health_metric_vis#16]
Hi, the health metric seems to display **wrong unit** while using Byte format in Number.
### Here's info:
   - Version: kibana 5.4.3
   - Changed the Number format in Index Patterns from -default- to Bytes:

![default](https://user-images.githubusercontent.com/13749575/28307813-b9a4cfec-6bd6-11e7-81a7-32cab50fc317.png)

   - Then applying same settings both on metric and health metric. 

### example:
![metricbug](https://user-images.githubusercontent.com/13749575/28307473-9ecd5974-6bd5-11e7-8059-26d074e4d94f.PNG)

**Comment by clamarque** [comment]
@KentingChen Hi! The bug is fixed. you can download the new release (5.4.3).
