### ISSUE TITLE
Add support for kibana 5.5.1

### ISSUE THREAD

**Issue by alias454** [clamarque/Kibana_health_metric_vis#18]
I downloaded the plugin and tried to install the source.zip but get type errors similar to this
https://github.com/elastic/kibana/issues/12707

I tried to bumble my way through some changes but was unsuccessful in making it work.

Please let me know if you need more information form me.

Regards,
Brandon

**Comment by austin-taylor** [comment]
It looks like the directory needs to be kibana/name_of_plugin

Then you can use sudo bin/kibana-plugin install file:///name_of_plugin.zip

I'll update the zip file and resubmit PR

**Comment by austin-taylor** [comment]
https://github.com/clamarque/kibana_health_metric_vis/pull/19

**Comment by clamarque** [comment]
@alias454 I will put soon a new release for 5.5.x. a release contain the source of code and the plugin functionnal (globaly with the name of plugin, for example kibana_health_metric_vis-5.5.x.) You can download this [here](https://github.com/clamarque/kibana_health_metric_vis/releases) next time. For now, I need to resolve some bugs before the release will be available
