### ISSUE TITLE
install on kibana 5.0 fails 

### ISSUE THREAD

**Issue by agonen** [clamarque/Kibana_health_metric_vis#2]
I've followed the instrunctions (clone+zipped) and got the following error 
`
root@master1:~/amihay# /data/elasticsearch50/kibana-5.0.0-linux-x86_64/bin/kibana-plugin install file:///tmp/kibana_health_metric_vis.zip
Attempting to transfer from file:///tmp/kibana_health_metric_vis.zip
Transferring 216517 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
`

**Comment by clamarque** [comment]
@agonen  Hi. It's normal, my plugin does not work on Kibana 5. A future release on Kibana 5 will soon be available.

**Comment by clamarque** [comment]
@agonen Hi! The plugin for kibana 5 is complete. Leave me a star if my project appeals to you.
