### ISSUE TITLE
Add support for kibana 5.6.1 

### ISSUE THREAD

**Issue by Granluc** [clamarque/Kibana_health_metric_vis#20]
Hi,

I'm trying to install your plugin on kibana 5.6.1.
I have change the version in the package.json file. 
But, I have this following error on my browser:

<< 
Fatal Error
TypeError: _modules2.default is undefined (http://kibana5-socle.pin.dolmen.bouyguestelecom.fr/bundles/kibana.bundle.js?v=15533:282)

Version: 5.6.1
Build: 15533

Error: TypeError: _modules2.default is undefined (http://kibana5-socle.pin.dolmen.bouyguestelecom.fr/bundles/kibana.bundle.js?v=15533:282)
[2502]/window.onerror@http://kibana5-socle.pin.dolmen.bouyguestelecom.fr/bundles/commons.bundle.js?v=15533:90:22028
>>

Regards,
Luc

**Comment by TRISAF** [comment]
Hi,
this plugin work's fine on 5.5 but not on 5.6.1
The error is:
Uncaught TypeError: Cannot read property 'get' of undefined (http://localhost:5601/bundles/kibana.bundle.js?v=15533:153)
Version: 5.6.1
Build: 15533
Error: Uncaught TypeError: Cannot read property 'get' of undefined (http://localhost:5601/bundles/kibana.bundle.js?v=15533:153)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15533:76:8876)

Any idea for fix this error?

Many thanks
Filippo

**Comment by clamarque** [comment]
Hi, I have update my plugin for kibana 5.6. You can download now the plugin [here](https://github.com/clamarque/kibana_health_metric_vis/releases).

**Comment by Granluc** [comment]
Thanks a lot !
