### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined (https://localhost:5601/atv/bundles/kibana.bundle.js?v=8467:324378)

### ISSUE THREAD

**Issue by xvdayou** [clamarque/Kibana_health_metric_vis#23]
Why is that? How do you deal with it?
![image](https://user-images.githubusercontent.com/25738893/34931107-dec0eb5c-fa07-11e7-97b5-041a9351e1c4.png)
![image](https://user-images.githubusercontent.com/25738893/34931125-fb3aaf5c-fa07-11e7-9315-354154eca1bf.png)

**Comment by clamarque** [comment]
@xvdayou hi. what is your version of kibana ?

**Comment by xvdayou** [comment]
@clamarque kibana-5.5.2 I download it in the same version

**Comment by xvdayou** [comment]
I think I know where the problem is. import is wrong

![1 5 7e flv9wf_ l 7b 7](https://user-images.githubusercontent.com/25738893/34970620-62062cd6-fab0-11e7-9a2d-7b66f372d518.png)
![5e6wisrx 46k7d m wwlf 1](https://user-images.githubusercontent.com/25738893/34970621-62386a16-fab0-11e7-8df0-dc3595d1f7a5.png)

**Comment by clamarque** [comment]
@xvdayou Sorry for the late reply. You right, I fix this problems . I will push soon a new release for kibana 5.5x. Thank you to use my plugin :+1:

**Comment by clamarque** [comment]
@xvdayou I fix the problems. You can now download the plugin for kibana 5.5.x [here](https://github.com/clamarque/kibana_health_metric_vis/releases/tag/v5.5). If you find a another bug, create a another issue. Thank you !
