### ISSUE TITLE
Support for Kibana 6.1.x

### ISSUE THREAD

**Issue by bwaang** [clamarque/Kibana_health_metric_vis#24]
Hi,

Was looking for support for Kibana 6.1.x, already started some of the transitioning work for you:

https://github.com/clamarque/kibana_health_metric_vis/pull/22

However couldn't figure out why `esResponse.hits.total` was not returning anything when it was using the tabifyAggsResponse even though the code in 5.6 & 6.1 looked the same.

**Comment by bwaang** [comment]
This may be helpful, in 5.6 (which works) the esResponse looks like:

![working-esreponse-5 6](https://user-images.githubusercontent.com/3912116/35112607-6782366c-fc33-11e7-815a-394b7d4fa5d1.png)

However in 6.1 the esResponse isn't loading total and the structure looks completely different:
![failing-esresponse-6 1](https://user-images.githubusercontent.com/3912116/35112627-77be7ebe-fc33-11e7-8a10-d610390686b6.png)

**Comment by clamarque** [comment]
@bwaang Hi! Thank you :+1:  ! sorry for the late. I will start working on it ;). I'll be back soon with some news.

**Comment by ghost** [comment]
Hi , I just installed this plugin in kibana5 but it is not reflecting in visualization. 
after done some changes as below still facing issues.
Error:Module not found: Error: Cannot resolve 'file' or 'directory' C:\project_elkStack\software\kibana-6.0.1-windows-x86_64\src\ui\public/template_vis_type in C:\project_elkStack\software\kibana-6.0.1-windows-x86_64\plugins\kibana_health_metric_vis-master\public


,
  "authors": [
  ""
  ],
  "license": "Apache-2.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "lint": "eslint",
    "start": "plugin-helpers start",
    "test:server": "plugin-helpers test:server",
    "test:browser": "plugin-helpers test:browser",
    "build": "plugin-helpers build",
    "postinstall": "plugin-helpers postinstall"
  },
  "devDependencies": {
    "@elastic/eslint-config-kibana": "0.0.2",
    "@elastic/plugin-helpers": "^6.0.0",
    "babel-eslint": "4.1.8",
    "chai": "^3.5.0",
    "eslint": "1.10.3",
    "eslint-plugin-mocha": "1.1.0"
  }

can you pleas help me on this

**Comment by ghost** [comment]
is this plugin available for version 6.1.1 for kibana? or please suggest what modification we do required fro that..

**Comment by bwaang** [comment]
@clamarque thanks for the response :) my guess is I need to populate an `aggConfig` object somewhere that gets eventually gets proccessed to the `esResponse` but just haven't had time to look into it.

Thanks for building such an awesome plugin :)

**Comment by Stono** [comment]
Hey, 
We're reallllllllllly like 6.1.2 support, please!  Any updates clamarque? :)

**Comment by clamarque** [comment]
Hello ! I come back with some news. @bwaang  the problem is that now they use React to generate their plugins. Indeed, the structures are the same but not the components. I need more time to understand and work on my plugin. thank you for your patience.

**Comment by clamarque** [comment]
@bwaang just look [here](https://github.com/elastic/kibana/blob/master/src/core_plugins/metric_vis/public/metric_vis_controller.js) , example on metric vis of kibana 6

**Comment by bwaang** [comment]
@clamarque thanks for the information, really appreciate your work on this!

**Comment by clamarque** [comment]
![capture du 2018-02-28 13-40-23](https://user-images.githubusercontent.com/3373009/36788115-02a3c77c-1c8d-11e8-8ba6-e8b74829f301.png)
 It's working ! I coming back with a new release for kibana 6.2.2 very soon (need test before).

**Comment by clamarque** [comment]
The version 6.x is out ! you can now download the new version [here](https://github.com/clamarque/kibana_health_metric_vis/releases) ! I advice to update kibana and elasticsearch at latest version (best manage of visualizations). Create a another issue if you find a bug. Thanks you :)
