### ISSUE TITLE
Issue installing 6.2.2 to official Kibana docker container

### ISSUE THREAD

**Issue by bwaang** [clamarque/Kibana_health_metric_vis#27]
Hi @clamarque,

I'm trying to install the plugin inside the docker container in elastic's official kibana docker images (using: `docker.elastic.co/kibana/kibana-oss:6.2.2`)

After running this inside the container

```
kibana-plugin install https://github.com/clamarque/kibana_health_metric_vis/releases/download/v6.2/kibana_health_metric_vis-6.2.2.zip
Attempting to transfer from https://github.com/clamarque/kibana_health_metric_vis/releases/download/v6.2/kibana_health_metric_vis-6.2.2.zip
Transferring 601240 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Killed
```

But after that it errors out:
![error-kibana](https://user-images.githubusercontent.com/3912116/37184970-e208de1e-22f2-11e8-8eda-249c56f21865.png)

Not sure if this is related to Elasticsearch's official docker container or the install itself.

**Comment by clamarque** [comment]
Hi @bwaang, sorry but I don't know how it works with docker. I had never tried this: /. I will have to search on this subject.

**Comment by bwaang** [comment]
No worries, hoping that it's just their container & their next release will work, I had an issue with the the `5` containers so I couldn't backport, so I to my own build.  I feel like their docker development isn't too stable yet :(

🤞 next version it'll just work

**Comment by clamarque** [comment]
Happy for you. don't hesitate to post a issue or another question and thank you for using my plugin;) (Close this issue)
