### ISSUE TITLE
Not working on Kibana 5.6.7

### ISSUE THREAD

**Issue by persefer** [clamarque/Kibana_health_metric_vis#29]
Hello, I have kibana 5.6.7 installed. I extracted zip files in to plugin directory as kibana/plugins/kibana_health_metric_vis-master/
then started kibana. But I cant see any new visulation option in Kibana Visualize section. Could you please help me?
Thank you very much

**Comment by clamarque** [comment]
@persefer Hi. Check the README please. He explain how to install a plugin in Kibana. Thank !
