### ISSUE TITLE
5.0.1

### ISSUE THREAD

**Issue by Findarato** [clamarque/Kibana_health_metric_vis#3]
No longer able to install with 5.0.1

**Comment by clamarque** [comment]
@Findarato Hi! Can you give me the error please ?

**Comment by tonykoval** [comment]
change version in package.json from 5.0.0 to 5.0.1

**Comment by Findarato** [comment]
@clamarque @Tonyko 

I was able to install once I adjusted the package.json file.  The problem I am having now is that it is not showing up as a Visualization I can create.

**Comment by clamarque** [comment]
@Findarato Hi ! Can you give me a screenshot ? I don't understand your problem. How does it come about?

**Comment by DavidHerBet** [comment]
Hi @clamarque, as specified in https://www.elastic.co/guide/en/kibana/current/kibana-plugins.html: 

> Plugin developers will have to release a new version of their plugin for each new Kibana release as a result.

If you create a tag with v5.0.1 changing package.json as @Tonyko said, it will be very well appreciated (in order to avoid downloading the zip and change it manually by ourselves).

**Comment by clamarque** [comment]
@DavidHerBet Hi! I update the package.json so. A new release is available

**Comment by DavidHerBet** [comment]
@clamarque thanks you very much :D
