### ISSUE TITLE
Support for 6.3.0

### ISSUE THREAD

**Issue by SamikshaJain** [clamarque/Kibana_health_metric_vis#31]
Is this supported on 6.3.0

**Comment by clamarque** [comment]
I am working on it

**Comment by amitendrak** [comment]
how about 6.5?

**Comment by gaby** [comment]
@clamarque any updates?

**Comment by clamarque** [comment]
@SamikshaJain wow ! sorry for this time... . You can download this release here: [v6.3.x](https://github.com/clamarque/kibana_health_metric_vis/releases/tag/v6.3.x)
