### ISSUE TITLE
Not working on Kibana 6.4.0 

### ISSUE THREAD

**Issue by bharatm89** [clamarque/Kibana_health_metric_vis#35]
Do we have this plugin for Kibana 6.4.0 ?
I tried to use master one but looks like it dint work

**Comment by clamarque** [comment]
@bharatm89 yes, it's normal.. Elastic change the composition of plugins when a new release up... I try to fix this.

**Comment by sethyes** [comment]
It's working for me on Kibana 6.4.2

**Comment by clamarque** [comment]
@bharatm89 You can download this version [here](https://github.com/clamarque/kibana_health_metric_vis/releases/tag/v6.4.x). enjoy !
