### ISSUE TITLE
Support for Kibana 6.5.4

### ISSUE THREAD

**Issue by gaby** [clamarque/Kibana_health_metric_vis#36]
Would it be possible to get a release for Kibana 6.5.x ? 

Thanks!

**Comment by porkiz** [comment]
I am currently fixing this plugin for 6.5.4.

https://github.com/clamarque/kibana_health_metric_vis/pull/37

In the meantime, it is semi working for now.

**Comment by gaby** [comment]
@porkiz Awesome, I can test it tomorrow. :-)

**Comment by clamarque** [comment]
@porkiz @gabrielcalderon I try to fix it this week ;)

**Comment by clamarque** [comment]
@porkiz @gabrielcalderon This version is available [here](https://github.com/clamarque/kibana_health_metric_vis/releases/tag/v6.5.x).
