### ISSUE TITLE
Support for Kibana 7.0.0

### ISSUE THREAD

**Issue by teguhbdy** [clamarque/Kibana_health_metric_vis#39]
This plugin is incompatible with Kibana 7.0.0.

**Comment by sancroth** [comment]
I second this. Installation with kibana 7.x.x fails.
Please add support for these versions, the gauges kibana offer do not work well when you add groups. This plugin is simple and perfect.

**Comment by clamarque** [comment]
Hi. I will work soon on this and make available futur release for 7.x.x and 6.x.x. Thank to use my plugin :)

**Comment by clamarque** [comment]
@teguhbdy @sancroth You can download it now, [here](https://github.com/clamarque/kibana_health_metric_vis/releases/tag/v7.0). I will keep to add the compatibility with another versions for the version 7.x.x
