### ISSUE TITLE
Reloading visualize background when "Apply changes"

### ISSUE THREAD

**Issue by DavidHerBet** [clamarque/Kibana_health_metric_vis#5]
Hi there, it would be great if background updates when you apply changes modifing thresholds.

To see what I say, go for a search that hits a count of **x** (15 for example), and then set critical threshold over it (20 for example) and press "apply changes" (play) button.

You will see nothing happens, unless you hit the search  again.

Thanks in advance!

**Comment by clamarque** [comment]
@DavidHerBet Hi! Why you don't start auto-refresh on kibana ? For example, a refresh about 5 seconds, you will see the modifications about thresholds.

**Comment by DavidHerBet** [comment]
Hi @clamarque, I put the issue because I think the normal flow when you use whatever visualization is to hit play to see how the changes apply, it would be a plugin enhancement, but what you suggest works perfectly, so thanks you! :D

**Comment by clamarque** [comment]
@DavidHerBet  Hi! i'm glad that you enjoy my plugin :) . I close this issue.
