### ISSUE TITLE
Cannot Install plugin 

### ISSUE THREAD

**Issue by OuesFa** [clamarque/Kibana_health_metric_vis#6]
Hello,

I'm using Kibana 4.5.1 on Ubuntu 14.04.4 LTS.

I downloaded the plugin using this link `https://github.com/clamarque/kibana_health_metric_vis/releases/download/v4.2/kibana_health_metric_vis-4.2.zip`
Trying to install command using : 
`sudo bin/kibana plugin -i health-metric-vis -u file:/path/to/kibana_health_metric_vis-4.2.zip`

I've this error message :1234:  
```
Installing health-metric-vis
Attempting to transfer from file:/home/ubuntu/Téléchargements/kibana_health_metric_vis-4.2.zip
Transferring 32282 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ./optimize/bundles/kibana.entry.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /opt/kibana/installedPlugins/health-metric-vis/public/health_metric_vis in /opt/kibana/optimize/bundles
     @ ./optimize/bundles/kibana.entry.js 129:0-54
"
```

Any Help please :+1:

**Comment by clamarque** [comment]
@OuesFa Hi! You need to replace the version in the file package.json with your version. I have tested this and it works well.

**Comment by OuesFa** [comment]
Thank you it worked fine :+1:

**Comment by nagetsum** [comment]
> You need to replace the version in the file package.json with your version

Do you mean following ?
unzip  kibana_health_metric_vis-4.2.zip
vim package.json
{
    "name": "health_metric_vis",
    "version": "<your kibana version.  e.g. 4.5.3>"  
}
and re-compress zip archive.

I'm using Kibana 4.5.3 and kibana_health_metric_vis-4.2.zip, it doesn't work.

**Comment by clamarque** [comment]
@n-agetsu Hi. Yes. replace your version in the version from package.json. Tell me if it's work fine?

**Comment by nagetsum** [comment]
@clamarque thanks for your response!
I tried rewrite package.json my kibana version(4.5.3), it doesn't work.
I'm using Kibana 4.5.3 Linux 64-BIT on Fedora 25.

I've following error message.
```
./kibana plugin -i health-metric-vis -u file:/home/agetsuma/elastic/plugin/kibana_health_metric_vis-4.2.zip 
Installing health-metric-vis
Attempting to transfer from file:/home/agetsuma/elastic/plugin/kibana_health_metric_vis-4.2.zip
Transferring 32558 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ../optimize/bundles/kibana.entry.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /home/agetsuma/elastic/kibana-4.5.1-linux-x64/installedPlugins/health-metric-vis/public/health_metric_vis in /home/agetsuma/elastic/kibana-4.5.1-linux-x64/optimize/bundles
     @ ../optimize/bundles/kibana.entry.js 127:0-54
```
Any help please.

**Comment by clamarque** [comment]
@n-agetsu I have tested myself, It's works fine on version 4.5.3. Check the architectury of repository: When you extract the files, you must see this: kibana_health_metric_vis-4.2\kibana_health_metric_vis-4.2.\assets (for example)

**Comment by clamarque** [comment]
@n-agetsu I see in your command that you use just 1 slash and not 3. Try with 3 slash like write in the readme: $KIBANA_HOME/bin/kibana plugin --install health-metric-vis -u file:///$HOME_DIRECTORY/kibana_health_metric_vis-4.2.zip

**Comment by nagetsum** [comment]
@clamarque work fine! thanks.
In my case, there was no need rewrite package.json my kibana version.

> you must see this: kibana_health_metric_vis-4.2\kibana_health_metric_vis-4.2.\assets (for example)
I tried this.

In error case,
```
zipinfo kibana_health_metric_vis-4.2.zip 
Archive:  kibana_health_metric_vis-4.2.zip
Zip file size: 32282 bytes, number of entries: 13
drwx---     6.3 fat        0 bx stor 16-Nov-18 15:51 assets/
drwx---     6.3 fat        0 bx stor 16-Nov-18 15:51 assets/img/
-rw-a--     6.3 fat    27487 bx defN 16-Nov-18 15:51 assets/img/demo.PNG
-rw-a--     6.3 fat      209 bx defN 16-Nov-18 15:51 index.js
...
```

In sucess case, add kibana_health_metric_vis-4.2 directory.
```
zipinfo kibana_health_metric_vis-4.2.zip 
Archive:  kibana_health_metric_vis-4.2.zip
Zip file size: 33498 bytes, number of entries: 14
drwxrwxr-x  3.0 unx        0 bx stor 17-Feb-15 09:02 kibana_health_metric_vis-4.2/
-rw-rw-r--  3.0 unx    11357 tx defN 16-Nov-18 15:51 kibana_health_metric_vis-4.2/LICENSE
-rw-rw-r--  3.0 unx     1378 tx defN 16-Nov-18 15:51 kibana_health_metric_vis-4.2/README.md
-rw-rw-r--  3.0 unx      209 tx defN 16-Nov-18 15:51 kibana_health_metric_vis-4.2/index.js
...
```
thank you for kind response!

**Comment by lisafitz** [comment]
I don't have an threshold for yellow. What's wrong? Thanks for any help.
<img width="308" alt="screen shot 2017-04-09 at 12 59 51 pm" src="https://cloud.githubusercontent.com/assets/26880795/24839241/bc309882-1d24-11e7-9b07-6579d5b23174.png">

**Comment by clamarque** [comment]
@lisafitz Hi. What version did you use?  4.x or 5.x ? I can see that you are not use my plugin but this [plugin](https://github.com/DeanF/health_metric_vis). Use my plugin for get a warning threshold.

**Comment by lisafitz** [comment]
5.0

On Apr 10, 2017, at 3:30 AM, Charles Lamarque <notifications@github.com> wrote:

@lisafitz <https://github.com/lisafitz> Hi. What version did you use? 4.x or 5.x ?
