### ISSUE TITLE
5.1.2

### ISSUE THREAD

**Issue by valugi** [clamarque/Kibana_health_metric_vis#7]
Hi,
Can you create a tag for the lastest Kibana version?
`Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [health_metric_vis]. Expected [5.1.2]; found [5.0.0]"`

**Comment by clamarque** [comment]
@valugi Hi, I'm sorry for responding so late. It's ok now. You can download this version [here](https://github.com/clamarque/kibana_health_metric_vis/releases/download/v5.1.2/kibana_health_metric_vis-5.1.2.zip).
