### ISSUE TITLE
Support for Kibana 5.2.1

### ISSUE THREAD

**Issue by kiambogo** [clamarque/Kibana_health_metric_vis#8]
Any chance this is supported in Kibana 5.2.1? Thanks!

**Comment by clamarque** [comment]
I don't know again if this worked on the new release. please, let me try and I accept after your pull request

**Comment by clamarque** [comment]
@kiambogo Hi! It's ok. I accepted your pull request. A new release is now available [here](https://github.com/clamarque/kibana_health_metric_vis/releases/tag/v5.2.1). Thank !
